/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminItemsNewRouteImport } from './routes/admin.items.new'
import { Route as AdminItemsIdRouteImport } from './routes/admin.items.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsNewRoute = AdminItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsIdRoute = AdminItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/item/$id': typeof ItemIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/items/$id': typeof AdminItemsIdRoute
  '/admin/items/new': typeof AdminItemsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/item/$id': typeof ItemIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/items/$id': typeof AdminItemsIdRoute
  '/admin/items/new': typeof AdminItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/item/$id': typeof ItemIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/items/$id': typeof AdminItemsIdRoute
  '/admin/items/new': typeof AdminItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/categories'
    | '/api/uploadthing'
    | '/item/$id'
    | '/admin/'
    | '/admin/items/$id'
    | '/admin/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/categories'
    | '/api/uploadthing'
    | '/item/$id'
    | '/admin'
    | '/admin/items/$id'
    | '/admin/items/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/categories'
    | '/api/uploadthing'
    | '/item/$id'
    | '/admin/'
    | '/admin/items/$id'
    | '/admin/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ItemIdRoute: typeof ItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items/new': {
      id: '/admin/items/new'
      path: '/items/new'
      fullPath: '/admin/items/new'
      preLoaderRoute: typeof AdminItemsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items/$id': {
      id: '/admin/items/$id'
      path: '/items/$id'
      fullPath: '/admin/items/$id'
      preLoaderRoute: typeof AdminItemsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminItemsIdRoute: typeof AdminItemsIdRoute
  AdminItemsNewRoute: typeof AdminItemsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminItemsIdRoute: AdminItemsIdRoute,
  AdminItemsNewRoute: AdminItemsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ItemIdRoute: ItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
